# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: Pinakin Kansara
google_analytics: Pinakin Kansara
title: Pinakin Kansara

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Pinakin Kansara

description: Pinakin Kansara
author:
  name: Pinakin Kansara
  email: pinakin.k.kansara@gmail.com
  github: https://github.com/pinakinkansara
  twitter: https://twitter.com/KansaraPinakin
  pinterest: asd123
  linkedin: https://www.linkedin.com/in/pinakinkansara/
  bio: Software Engineer @ Matsercard
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
sidebar_background_image: https://media.licdn.com/dms/image/C5103AQHuPmYbqhe7Xw/profile-displayphoto-shrink_200_200/0?e=1575504000&v=beta&t=liIow8vjuIFeggVmcI38sTwSuDwPWWkanSXmuUPC7VU

BASE_PATH:

plugins:
  - jekyll-paginate
