theme: jekyll-theme-architect
name: Pinakin Kansara
avatar: https://avatars3.githubusercontent.com/u/7393671?s=400&u=3f12d2226ee8eaaa276e7bd2af2c3db450c4d6c7&v=4
title: Pinakin Kansara
description: Software Engineer|| @ [Mastercard](https://www.mastercard.co.in/en-in.html)
